### ISSUE TITLE
permission denied: ./setup-seafile.sh ???

### ISSUE THREAD

**Issue by ky0nch3ng** [haiwen/seafile-server#172]
➜  seafile-server-6.3.1 chmod 777 setup-seafile.sh
➜  seafile-server-6.3.1 ./setup-seafile.sh
zsh: permission denied: ./setup-seafile.sh
➜  seafile-server-6.3.1 lsa
total 152K
drwxr-xr-x  6 root root 4.0K Jun  9 16:51 .
drwxr-xr-x  3 root root 4.0K Jul  5 17:12 ..
-rw-rw-r--  1 root root  12K Jun  9 16:51 check_init_admin.py
-rwxrwxr-x  1 root root 1.8K Jun  9 16:51 reset-admin.sh
drwxr-xr-x  2 root root 4.0K Jun  9 16:51 runtime
-rwxrwxr-x  1 root root 1.9K Jun  9 16:51 seaf-fsck.sh
-rwxrwxr-x  1 root root 3.3K Jun  9 16:51 seaf-fuse.sh
-rwxrwxr-x  1 root root 2.8K Jun  9 16:51 seaf-gc.sh
drwxr-xr-x  6 root root 4.0K Jun  9 16:51 seafile
-rwxrwxr-x  1 root root 5.1K Jun  9 16:51 seafile.sh
drwxrwxr-x 13 root root 4.0K Jun  9 16:49 seahub
-rwxrwxr-x  1 root root 7.6K Jun  9 16:51 seahub.sh
-rwxrwxr-x  1 root root  53K Jun  9 16:51 setup-seafile-mysql.py
-rwxrwxr-x  1 root root 2.6K Jun  9 16:51 setup-seafile-mysql.sh
-rwxrwxrwx  1 root root  23K Jun  9 16:51 setup-seafile.sh
drwxrwxr-x  4 root root 4.0K Jun  9 14:00 upgrade
➜  seafile-server-6.3.1 whoami
root

**Comment by freeplant** [comment]
Please ask the question in our forum https://forum.seafile.com
