### ISSUE TITLE
[7.0] upgrade SQL: Table 'seahub_db.TotalStorageStat' doesn't exist

### ISSUE THREAD

**Issue by foxel** [haiwen/seafile-server#234]
In 7.0 upgrade SQL there are operations to alter `TotalStorageStat` table which is not mentioned in any SQL earlier. This table does not exist on 6.3 installation and the upgrade SQL fails.

https://github.com/haiwen/seafile-server/blob/89db991f86a9f105d3aa609e573fb2ee5100e656/scripts/upgrade/sql/7.0.0/mysql/seahub.sql#L31

Also strange that these alter instructions are present only for MySQL.

**Comment by freeplant** [comment]
In the official script, it is a warning. The warning can be ignored.

**Comment by foxel** [comment]
@freeplant does it mean the upgrade SQLs are OK to be run multiple times?

**Comment by freeplant** [comment]
Yes, upgrade SQLs are OK to be run multiple times.

**Comment by foxel** [comment]
OK. Thanks for the answers
