### ISSUE TITLE
Static tags

### ISSUE THREAD

**Issue by eolianoe** [haiwen/seafile-server#27]
Hello,

I'm packaging the seafile suite in the [AUR](https://aur.archlinux.org/packages.php?K=seafile) for ArchLinux.
It seems that the github archives for specific tags are regenerated when new commits are added leading to different checksums for the archive, which is a bit annoying. I'm posting the issue in the this repo but this happens for various components of seafile.

For instance, the 6.0.8-server tag was generated two days ago with the commit d78176e015fb0c0aba5a3eb2620e9b154bbedc71 but now the 6.0.8-server tag links to commit 345d4ad286be4cc95ffdf56991d5fbacb0cc040f leading to two different archive.

Would it be possible to generate proper tags linking to a unique commits and not regenerate the archive ? For instance, commit 345d4ad286be4cc95ffdf56991d5fbacb0cc040f should appear in 6.0.8.1 release or in the 6.0.9 but not in 6.0.8 as the tag was generated earlier.

Thanks by advance,
eolianoe

**Comment by VGoshev** [comment]
I have exactly the same issue with Gentoo ebuilds and docker images

**Comment by killing** [comment]
Hi

That's because we found bugs in the old tag and updated it. At that time 6.0.8 is not released yet so changing the tag should not be a problem. I suggest you update AUR packages after we officially announced a new version of server.

**Comment by eolianoe** [comment]
Ok I didn't understand the fact that 6.0.8 was not officially released. I use the [rss feed](https://github.com/haiwen/seafile-server/tags.atom) to be notified about new release and I was thinking that git tags are official release.

Would it be possible to tag only when the release is done or give us a proper way to detect official release?

**Comment by freeplant** [comment]
Our automatically packaging/testing system depends on Github tags to packaging and testing. If there is a bug found in the old tag, we will have to update it. You can watch https://forum.seafile.com/c/announcements when the final version is released.

**Comment by eolianoe** [comment]
Ok thanks for the explanation.
Could your packaging/testing system use the sha of the commits rather than the tag to simplify the packaging process?

If I understand correctly the 6.0.4 version of the client is not yet released as there is no [announcement](https://forum.seafile.com/c/announcements), even if the [6.0.4 tag](https://github.com/haiwen/seafile-client/releases/tag/v6.0.4) is already created?

**Comment by freeplant** [comment]
> Could your packaging/testing system use the sha of the commits rather than the tag to simplify the packaging process?

We can't change the process recently. Using sha of the commits is also complicated because there are 4 repos needed and 8 repos needed for the professional edition.

The 6.0.4 client is not released yet.  We are still testing the new version. Normally, we announce the release one or two days after tagging.

**Comment by eolianoe** [comment]
Ok, I'll wait a few days after the tags to update the various packages.
