### ISSUE TITLE
web api Delete File always return http 200 with "succes"

### ISSUE THREAD

**Issue by SebastienLQ** [haiwen/seafile-server#30]
hello ! 

The api return 200 http code with a Jsend response  "success", even if the file isn't in a Repo : 
HTTP code 204 should be expected, or a Jsend  response "No content"

GET on https://xxxx.xx/api2/repos/002a5bfd-4626-4147-8361-b2ed3e987dbf/file/detail/?p=/test
404
```
{
    "error_msg": "File not found."
}

```
DELETE on https://xxxx.xx/api2/repos/002a5bfd-4626-4147-8361-b2ed3e987dbf/file/?p=/test
200

> "success"

**Comment by shoeper** [comment]
Is this issue still present?

cc: @imwhatiam

**Comment by freeplant** [comment]
When writing an API for bulk deleting files, we find that it is more convenient to return 200 when some files do not exist. For example, if the caller ask to delete 20 files, but one file not exist, it is better to return 200. For consistent, we decide to not treat file not exist as an error. So we don't have a plan to change the behaviour for this API to make it consistent with bulk deletion API.

**Comment by shoeper** [comment]
I don't think this is good.

Does this API even allows deleting multiple files at once? Even for such an API I'd at least return an error code containing failed items and a reason.
