### ISSUE TITLE
Seahub stops accepting logins; `get_emailusers()` returns an empty array

### ISSUE THREAD

**Issue by rinogo** [haiwen/seafile-server#32]
After setting up Seahub, everything works great for a while.  After a few weeks, I can't log in anymore.  Even though I'm providing the right email and passwords, I'm not allowed in.

When I restart Seahub, I get the message:

"It's the first time you start the seafile server. Now let's create the admin account"

This error message is inaccurate - Seahub was running just fine previously.

I've tracked the issue down to [line 292 of `check_init_admin.py`](https://github.com/haiwen/seafile-server/blob/master/scripts/check_init_admin.py#L292).  It contains the call, `self.rpc_client.get_emailusers('DB', 0, 1)`.  The call is returning an empty array (`[]`) which makes the script think that this is the first execution.  However, my database shows many users.  (After all, I did have Seahub working previously).

![image](https://cloud.githubusercontent.com/assets/3732514/24163088/22ffbad4-0e2f-11e7-9647-2af595902821.png)

When I manually include a call to `count_emailusers()`, the return value is `-1`.

I'm not sure what's going on.  Is it possible that the server isn't successfully connecting to the database?  If that's a problem, I would imagine that there would be a different (more helpful) error message...

Maybe there's a "process owner"/permissions issue?  I'm starting the server as root, though... Here's the command I'm using:

`/opt/seafile/seafile-server-latest/seafile.sh start && /opt/seafile/seafile-server-latest/seahub.sh start-fastcgi`

I'm kind of out of ideas... Please help!

**Comment by rinogo** [comment]
Minor update: Restarting MySQL seems to temporarily fix the issue.  That is, Seafile (and its various components) seem to start up and I can log in.  However, this is only a temporary fix; the problem returns.

Given that restarting MySQL temporarily fixes the problem, it makes me think that it must be something to do with the connection between Seafile and MySQL.  Perhaps the connection gets interrupted/aborted/etc and Seafile needs to re-establish the connection, but doesn't...

Any thoughts?

**Comment by shoeper** [comment]
This is very unlikely a Seafile bug. It would fit better in the forum (https://forum.seafile.com/), thus.

**Comment by rinogo** [comment]
Thanks, @shoeper!  Can you please give a little more information on why it's unlikely to be a Seafile bug?  Thank you in advance! :)

**Comment by killing** [comment]
This also looks like environmental problem to me. I'm closing this thread. The discussion can be continued on forum.
