### ISSUE TITLE
Seafile Server 6.1.2 mysql errors

### ISSUE THREAD

**Issue by Ultima1252** [haiwen/seafile-server#66]
Hello, I just upgraded seafile 6.1.1 to 6.1.2 and cannot access my libraries. The Seafile.log has errors like this:

`[08/16/2017 00:29:40] ../common/seaf-db.c(425): Error prepare statement SELECT r.repo_id, s.size, b.commit_id, fc.file_count FROM Repo r LEFT JOIN Branch b ON r.repo_id = b.repo_id LEFT JOIN RepoSize s ON r.repo_id = s.repo_id LEFT JOIN RepoFileCount fc ON r.repo_id = fc.repo_id WHERE r.repo_id = ? AND b.name = 'master': mysql_stmt_prepare failed: Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation '='.`

Running FreeBSD 11 Stable r321401.

**Comment by freeplant** [comment]
What page do you visit when the error occur? The repo list page should not call this function. Can you show the error in seahub_django_request.log?

**Comment by Ultima1252** [comment]
When going to the Seafile site after login, clicking on a library, like My Library under the My Libraries tab.  I think it displays as no library found.

I'm not sure why the time stamps are different, but this is the error.
seahub_django_request.log:
`2017-08-15 20:30:08,049 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /api/v2.1/admin/system-library/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/www/haiwen/seafile-server/seahub/seahub/api2/endpoints/admin/system_library.py", line 37, in get
    result['name'] = repo.repo_name
AttributeError: 'NoneType' object has no attribute 'repo_name'`

**Comment by Ultima1252** [comment]
seahub.log:
`2017-08-15 20:29:45,016 [ERROR] seahub.api2.endpoints.admin.sysinfo:113 get Failed to get total file number from db.                                                                                                                          
2017-08-15 20:29:59,082 [ERROR] seahub.api2.endpoints.admin.sysinfo:113 get Failed to get total file number from db.                                                                                                                          
2017-08-15 20:30:12,080 [ERROR] seahub.api2.endpoints.admin.sysinfo:113 get Failed to get total file number from db.`

**Comment by Ultima1252** [comment]
Is there a character set change or enforcement for mysql in the recent version? It looks like the error is conflict in user, (my) Collation being utf8_general_ci and the new version being utf8_unicode_ci.

**Comment by Ultima1252** [comment]
Took some time and tested commit hashes to find when the offending commit starts. d16737b works fine. The next commit ab08ec5 returns partially corrupted data to the client. Every commit after that returns error library doesn't exist.

**Comment by killing** [comment]
@Ultima1252 Do you have the same error when running the reported SQL in mysql client?

**Comment by Ultima1252** [comment]
Running the SELECT query from the first post? Didn't test it in mysql client, was assuming some of these names were variables that don't translate in log.

**Comment by Ultima1252** [comment]
Finally got around to changing my database collation to utf8_unicode_ci and everything seems to be working as expected. 

I suggest adding a note in the changelog that mysql users should verify database collation prior to updating.
