### ISSUE TITLE
Seafile Server 32-bit

### ISSUE THREAD

**Issue by maxolasersquad** [haiwen/seafile-server#72]
The [download page](https://www.seafile.com/en/download/) has traditionally had links for 32-bit and 64-bit builds of seafile-server for Linux. As of the newly-minted 6.2.0, only 64-bit builds are available. I have a very old machine that acts as my seafile server and it has a 32-bit processor. Are 32-bit builds no longer going to be offered via the download page?

**Comment by shoeper** [comment]
I think it's only because 6.2 is beta.

The changelog does not mention a 32-bit build drop so far.

**Comment by shoeper** [comment]
I found out it is actually available but just not listed.

You can get it at https://download.seadrive.org/seafile-server_6.2.0_i386.tar.gz

**Comment by maxolasersquad** [comment]
Awesome. Thanks.
