### ISSUE TITLE
API doesn't include a "List all organizations" (admin-only) call

### ISSUE THREAD

**Issue by mathiasaerts** [haiwen/seafile-server#79]
There are many organization-related API calls available in the Seafile web API v2.1 (as documented on https://manual.seafile.com/develop/web_api_v2.1.html#admin-only-organization), but an important one is missing: "List all organizations".

It could be implemented in an API call like:
GET `/api2/organization/`
or
GET `/api/v2.1/admin/organizations/`

And, in addition, an organization detail call could be added to retrieve details for a single organization:
GET `/api2/organization/{org_id}`
or
GET `/api/v2.1/admin/organizations/{org_id}`

Is there any reason why these calls are missing? They would help a great deal in automating the configuration of the Seafile server.

**Comment by BenoitGEORGELIN** [comment]
Any chance to get an answer ?

**Comment by imwhatiam** [comment]
These two apis will be added in 6.3.9 pro.
